### ISSUE TITLE
What is this ridiculous joke?

### ISSUE THREAD

**Issue by acrolink** [Haeresis/vanilla-js#3]
« What is this ridiculous joke? »

**Comment by MachinisteWeb** [comment]
Yeah @acrolink :) You are totally right. The first lines are IT joke. i.e. there is no dependency needed to use pure JavaScript from the browser. That is called « ironie » in French because you are enought proof to understand the subject isn't serious.

However, this repository is useful for real. This resource is useful to pass from jQuery to pure JavaScript coding style (called Vanilla JS) for creating JavaScript libraries easily without jQuery dependencies. It's the goal. All values presented are also true performance value based on codepen provided.

That's help you to answer your question?

**Comment by acrolink** [comment]
I have looked inside vanilla.js and there was nothing, did not pay attention to documentation. Interesting but as long as the code is executed in the client side, I would sacrifice some speed in favour of jQuery's shortcuts.

**Comment by MachinisteWeb** [comment]
Sure. In a non-shared-library-context the utility is more contestable.
